export type {
  GridAxis,
  GridBounds,
  GridCanvas,
  GridEdges,
  GridHeightMode,
  GridItem,
  GridItemConstraints,
  GridItemPolicy,
  GridItemSize,
  GridLayout,
  GridPadding,
  GridPoint,
  GridRect,
  GridResizeEdge,
  GridSize,
  GridSizeMode,
} from './model'
export {
  DEFAULT_CANVAS,
  DEFAULT_SNAP_DISTANCE,
  EMPTY_PADDING,
  MIN_ITEM_SIZE,
  isFixedHeight,
  isFixedOnAxis,
  isFixedWidth,
  isGhost,
  isLocked,
} from './model'

export type { SolveStrategy, TraceCallback, TraceEvent } from './instrumentation'

export {
  boundsFromCanvas,
  canPlaceItem,
  canvasInnerHeight,
  canvasInnerRect,
  canvasInnerWidth,
  canvasesEqual,
  clampItem,
  cloneItems,
  contentBottom,
  contentRight,
  createItem,
  enforceMinimumGaps,
  findLayoutViolations,
  fitCanvasToContent,
  inferGap,
  itemArea,
  itemBottom,
  itemRight,
  layoutIsValid,
  normalizeCanvas,
  normalizeItem,
  normalizeItems,
  normalizeLayout,
  normalizePadding,
  overlapArea,
  pointInRect,
  rectToEdges,
  rectToViewportEdges,
  rectsOverlap,
  rectsViolateGap,
  resizeRect,
  roundItem,
  toCanvasItem,
  toInnerItem,
  type LayoutViolation,
} from './geometry'

export {
  applyGap,
  preserveGaps,
  projectFloatingRect,
  projectItemsByChain,
  projectItemsBySegments,
  projectLayout,
  roundItemRects,
  scaleItems,
  syncFixedDimensions,
  type ApplyGapOptions,
  type ProjectOptions,
  type ProjectionStrategy,
} from './projection'

export {
  edgeAlignedSlots,
  moveItem,
  placeItem,
  pushAndShrinkSiblings,
  resizeByShrinkingNeighbors,
  resizeItem,
  scaleSizeBetweenCanvases,
  transferItem,
  type MoveItemInput,
  type NewGridItem,
  type PlaceItemInput,
  type ResizeItemInput,
  type SolveOptions,
  type SolveResult,
  type TransferItemInput,
  type TransferResult,
} from './solver'

export {
  compactLayout,
  findContainerAt,
  findFirstUnlockedAncestor,
  flattenLayout,
  getAncestors,
  getDescendants,
  gridNodeAdapter,
  hitTest,
  isDirectChildOfContained,
  isInsideLockedSubtree,
  markLockedItems,
  projectItemToRoot,
  projectItemsToRoot,
  renderLayoutForRect,
  rootPointToContainer,
  scaleSizeBetweenContainers,
  toRenderedLayout,
  type CompactOptions,
  type CompactResult,
  type FindContainerOptions,
  type FlatItem,
  type FlatLayout,
  type FlattenOptions,
  type GridNode,
  type GridNodeBehavior,
  type GridTreeAdapter,
} from './nested'

export { applyPreset, type LayoutPreset, type PresetOptions } from './presets'
